version: '3.7'

services:
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - ADMIN_KEY=7fbae5db-37bb-4dc5-a9f5-115878c6bcb0
      - API_RSA_PUBLIC_KEY=/app/equal-shares-api-public-key.pem
      - API_RSA_PRIVATE_KEY=/app/equal-shares-api-private-key.pem
    volumes:
      - ./backend/equal-shares-api-private-key.pem:/app/equal-shares-api-private-key.pem
      - ./backend/equal-shares-api-public-key.pem:/app/equal-shares-api-public-key.pem
