name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Source
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - name: Install and Configure Poetry
        uses: snok/install-poetry@v1
        with:
            version: 1.7.1
            virtualenvs-create: false
      - name: Set up NodeJS 21
        uses: actions/setup-node@v4
        with:
            node-version: '21.5.0'
      - name: Install backend Dependencies
        working-directory: ./backend
        run: |
            poetry install
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
            npm ci
      - name: Lint
        run: |
            make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Source
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - name: Install and Configure Poetry
        uses: snok/install-poetry@v1
        with:
            version: 1.7.1
            virtualenvs-create: false
      - name: Set up NodeJS 21
        uses: actions/setup-node@v4
        with:
            node-version: '21.5.0'
      - name: Install backend Dependencies
        working-directory: ./backend
        run: |
            poetry install
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
            npm ci
      - name: Test
        run: |
            make test
