name: Lint

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Source
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - name: Install Poetry
        run: |
            pip install poetry@1.7.1
      - name: Set up NodeJS 21
        uses: actions/setup-node@v4
        with:
            node-version: '21.5.0'
      - name: Install backend Dependencies
        working-directory: ./backend
        run: |
            poetry config virtualenvs.create false
            poetry install
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
            npm ci
      - name: Lint
        run: |
            make lint
